title: bczyz's research blog
description: >- 
        bczyz's cyber security research blog
baseurl: "/"
url: "https://bczyz1.github.io" 
img: "/img"
author: bczyz1
twitter_username: bczyz1
github_username:  bczyz1
linkedin_username: bartłomiej-czyż-91416943
linkedin_username_visible: bczyz1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
minima:
        skin: dark

